name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Roda o deploy em cada push na branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Faz o checkout do repositório

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Configura o Node.js
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install  # Instala as dependências do projeto

    - name: Build project
      run: npx webpack --config webpack.config.js  # Compila o projeto com Webpack

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Ação para deploy no GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs  # Publica o conteúdo da pasta docs/
